### ISSUE TITLE
Bad URL for `conda-repo-cli`

### ISSUE THREAD

**Issue by jamespreed** [anaconda/anaconda-client#716]
This is slightly off-topic.  
The v6 API uses the `conda-repo-cli` package instead of the anaconda client package.  The listed URL for conda-repo-cli on anaconda.org is https://anaconda.org/anaconda/conda-repo-cli.  

However, this link gives a 404.  I am not sure where to add issues and look at documentation.

**Comment by mattkram** [comment]
@jamespreed can you please provide any additional information for what you are trying to do? `conda-repo-cli` is our current CLI for Package Security Manager on-prem, and the repo is currently private, which is why you may see a 404.

If you are looking for documentation for `conda-repo-cli`, I believe that information is here: https://business-docs.anaconda.com/en/latest/user/cli.html

**Comment by jamespreed** [comment]
> the repo is currently private, which is why you may see a 404

That is my answer.  I was trying to view the code.
